import java.sql.ResultSet;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSetMetaData;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.

/**
*
 * @author Roshaann 2.7 gpa
 */
public class fin_Bk extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	static Connection connect = null;
	/**
     * Creates new form fined_Bk
     */
    public fin_Bk() {
        this.setLocation(325, 150);
        initComponents();
    }
	public void function()
	{
		String Sql = "Select DISTINCT bookinfotable.BookName,bookinfotable.AurthorName,category.Title,finetable.BorrowwerID,finetable.TotalFine from bookinfotable JOIN category on bookinfotable.CategoryLinked=category.Category_ID JOIN bookissuereturntable on bookinfotable.BookID=bookissuereturntable.bookid JOIN finetable on bookissuereturntable.FineID=finetable.FineID";
	    try 
	    {
	    	try {
	        	PreparedStatement  pst = (PreparedStatement) connect.prepareStatement(Sql);
	    		ResultSet rs=pst.executeQuery();
	    		ResultSetMetaData RsMD =(ResultSetMetaData) rs.getMetaData();
	    		int Columns =RsMD.getColumnCount();
	    		DefaultTableModel dtm= new DefaultTableModel();
	    		Vector Col_names =new Vector();
	    		Vector Data_rows =new Vector();
	    		for(int i=1;i<=Columns;i++)
	    		{
	    			Col_names.addElement(RsMD.getColumnName(i));
	    		}
	    		dtm.setColumnIdentifiers(Col_names);
	    		while(rs.next())
	    		{
	    			Data_rows= new Vector();
	    			for(int i=1;i<=Columns;i++)
	    			{
	    				Data_rows.addElement(rs.getString(i));
	    			}
	    			dtm.addRow(Data_rows);	
                                
	    		
	    		}
	    		
	    	   JOptionPane.showMessageDialog(null,dtm.getValueAt(0, 1));
	        } 
	        catch (Exception e)
	        {
	            JOptionPane.showMessageDialog(null, e);
	        }	 
            
	    } 
	    catch (Exception e)
	    {
			JOptionPane.showMessageDialog(null,"Errors");
		}	 

	
		}
		
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fined_Bk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fined_Bk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fined_Bk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fined_Bk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fin_Bk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
