
//-------import Server.DbConnect;
//------import Server.SellBook_Server;

import java.io.IOException;
import java.net.SocketException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ButtonGroup;

import com.mysql.jdbc.ResultSetMetaData;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.ImageIcon;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Roshaann 2.7 gpa
 */
public class SellB extends javax.swing.JFrame {
String search;
String searchValue;
//static public SellBook_Server sb_s =new SellBook_Server();

    /**
     * Creates new form SellB
     */
    public SellB() {
        initComponents();
        this.setResizable(false);
    	this.setLocation(325, 150);
        
        ImageIcon i=new ImageIcon("sell.jpg");
       JLabel l=new JLabel(i);
       l.setBounds(0, 0, i.getIconWidth(), i.getIconHeight());
       
        
  
      
      this.back.setBounds(10,10,70,30);
      this.back.setVisible(true);
      
      this.back.setText("Back");
      this.add(back);
      this.add(l);
        
        this.back.addActionListener(new ActionListener(){
            

            @Override
            public void actionPerformed(ActionEvent e) {
           	o();
            }
        });
        
                
                
                
                
                
      /*  JButton bt=new JButton();
        bt.setBounds(80,10,50,50);
        bt.setText("hi");
        this.add(bt);
        bt.addActionListener(new ActionListener(){
            

            @Override
            public void actionPerformed(ActionEvent e) {
            	
            }
        });  */
        
        
        
        ButtonGroup bg=new ButtonGroup();
        tf_bk_cat.setEnabled(false);
        tf_au_nme.setEnabled(false);
        bg.add(btn_au_srch);
        bg.add(btn_cat_srch);
      
        
        //sb_s.f();
    }
    
     public void o(){
        menu m=new menu();
             
               this.setVisible(false);
               
                m.setVisible(true);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
 
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_au_nme = new javax.swing.JTextField();
        btn_au_srch = new javax.swing.JRadioButton();
        btn_cat_srch = new javax.swing.JRadioButton();
        btn_Push = new javax.swing.JButton();
        tf_bk_cat = new javax.swing.JTextField();
        back=new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        
        jLabel1.setText("Book category");

        jLabel2.setText("Author name");

        tf_au_nme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                au_nmeActionPerformed(evt);
            }
        });

        btn_au_srch.setText("Author search");
        btn_au_srch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                au_srchActionPerformed(evt);
            }
        });

        btn_cat_srch.setText("Category search");
        btn_cat_srch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cat_srchActionPerformed(evt);
            }
        });

        btn_Push.setText("Push Request");
        btn_Push.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PushActionPerformed(evt);
            }
        });

        tf_bk_cat.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                bk_catInputMethodTextChanged(evt);
            }
        });
        tf_bk_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bk_catActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Push, javax.swing.GroupLayout.PREFERRED_SIZE, 203, 

javax.swing.GroupLayout.PREFERRED_SIZE)
                          
                         
                        
                        
                        
                        
                    .addGroup(layout.createSequentialGroup()
                     
                         .addComponent(btn_au_srch)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cat_srch))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_bk_cat, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(tf_au_nme))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_bk_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_au_nme, javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_au_srch)
                    .addComponent(btn_cat_srch))
                .addGap(18, 18, 18)
                .addComponent(btn_Push)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void au_srchActionPerformed(java.awt.event.ActionEvent evt) {                                        
        tf_bk_cat.setText("");
        tf_bk_cat.setEnabled(false);
        tf_au_nme.setEnabled(true);
         search="author";
    }                                       

    private void cat_srchActionPerformed(java.awt.event.ActionEvent evt) {                                         
        tf_au_nme.setText("");
        tf_au_nme.setEnabled(false);
        tf_bk_cat.setEnabled(true);
         search="book";
    }                                        

    private void au_nmeActionPerformed(java.awt.event.ActionEvent evt) {                                       

    }                                      

    private void bk_catActionPerformed(java.awt.event.ActionEvent evt) {                                       

    }                                      

    private void bk_catInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {                                       

       
        // TODO add your handling code here:
    }                                             

    private void PushActionPerformed(java.awt.event.ActionEvent evt) {
    	
      if(search.compareToIgnoreCase("book")==0)
      {
    	  searchValue="2";
    	  searchValue+=tf_bk_cat.getText();
    	  
          try 
          {
              UDP udp= new UDP(searchValue);
              udp.send();
             
          
              
            //  sb_s.query();
          } 
          catch (SocketException ex) 
          {
              Logger.getLogger(SellB.class.getName()).log(Level.SEVERE, null, ex);
          }
           catch (IOException ex)
          {
              Logger.getLogger(SellB.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
      if(search.compareToIgnoreCase("author")==0){
    	  searchValue="1";
      searchValue+=tf_au_nme.getText();
       try {
             UDP udp= new UDP(searchValue);
            
          } catch (SocketException ex) {
              Logger.getLogger(SellB.class.getName()).log(Level.SEVERE, null, ex);
          } catch (IOException ex) {
              Logger.getLogger(SellB.class.getName()).log(Level.SEVERE, null, ex);
          }
      } 
    }                                    
        interface io{
           void rr();
        }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new SellB().setVisible(true);
            }
        });
        //sb_s.main(null);
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btn_Push;
    private javax.swing.JTextField tf_au_nme;
    private javax.swing.JRadioButton btn_au_srch;
    private javax.swing.JTextField tf_bk_cat;
    private javax.swing.JRadioButton btn_cat_srch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton back;
    // End of variables declaration                   
}
